### ISSUE TITLE
How to use for dd  MiniProject?

### ISSUE THREAD

**Issue by YanwuSenlu** [ant-move/Vant-Aliapp#1]
I create an dd mini-project with the dd/vant-app;
but In the demo, I click the '基础组件'，
console report：
`TypeError: Cannot read property 'children' of undefined
    at Object.onClick (http://127.0.0.1:62709/index.worker.js?t=1568603227584:10517:37)
    at Object.methods.(anonymous function) [as onClick] (http://127.0.0.1:62709/index.worker.js?t=1568603227584:7591:23)
    at _.triggerEvent (https://g.alicdn.com/dingding/appx-sdk/1.7.67/af-appx.worker.ide.js:2178:104)
    at Object.triggerEventHandlers.(anonymous function) [as onClick] (https://g.alicdn.com/dingding/appx-sdk/1.7.67/af-appx.worker.ide.js:2165:56)
    at Object.triggerEvent (http://127.0.0.1:62709/index.worker.js?t=1568603227584:7876:30)
    at Object.$emit (http://127.0.0.1:62709/index.worker.js?t=1568603227584:12047:31)
    at Object.methods.(anonymous function) [as $emit] (http://127.0.0.1:62709/index.worker.js?t=1568603227584:7591:23)
    at Object.onClick (http://127.0.0.1:62709/index.worker.js?t=1568603227584:10085:18)
    at Object.methods.(anonymous function) [as onClick] (http://127.0.0.1:62709/index.worker.js?t=1568603227584:7591:23)
    at PageComponent.triggerComponentEvent (https://g.alicdn.com/dingding/appx-sdk/1.7.67/af-appx.worker.ide.js:1074:76)`

**Comment by YanwuSenlu** [comment]
It may cause by  @YanwuSenlu  /dist/collapse-item line 11 
`linked(parent) {
          console.log(parent)
          this.parent = parent;
        }`
not work

**Comment by amap-appx** [comment]
Vant-Aliapp not support ding-talk yet,  the good news is  vant-aliapp for ding-talk is on the way
