### ISSUE TITLE
支付宝小程序使用自定义组件 ide报错 

### ISSUE THREAD

**Issue by chen-can** [ant-move/Vant-Aliapp#2]
在 IDE 中的 详情 > 项目配置 中，勾选 启用 component2 编译 。
使用的是 uni-app

报出以下错误
TypeError: Cannot read property 'mountedHandles' of undefined
at Object.didMount (http://127.0.0.1:53737/index.worker.js?t=1568796559287:18457:82)
at http://127.0.0.1:53737/index.worker.js?t=1568796559287:17322:24
at Array.forEach ()
at Object.ctx.(anonymous function) (http://127.0.0.1:53737/index.worker.js?t=1568796559287:17321:31)
at g (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:7:62991)
at o.i.componentDidMount (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:7:65402)
at zr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:50136)
at Fr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:47604)
at Nr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:47108)
at Object.batchedUpdates (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:53461)
setTimeout (async)
e.setTimeout @ af-appx.worker.ide.min.js:7
console.error @ bridge.js:1
En @ af-appx.worker.ide.min.js:24
Ln.o.function.o.componentDidCatch.n.callback @ af-appx.worker.ide.min.js:24
ht @ af-appx.worker.ide.min.js:24
gt @ af-appx.worker.ide.min.js:24
zr @ af-appx.worker.ide.min.js:24
Fr @ af-appx.worker.ide.min.js:24
Nr @ af-appx.worker.ide.min.js:24
batchedUpdates @ af-appx.worker.ide.min.js:24
K @ af-appx.worker.ide.min.js:7
renderVDOM @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
runBatch @ af-appx.worker.ide.min.js:7
updateVDOM @ af-appx.worker.ide.min.js:7
initComponents @ af-appx.worker.ide.min.js:7
preload @ af-appx.worker.ide.min.js:7
load @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
Promise.then (async)
R @ af-appx.worker.ide.min.js:7
L @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
(anonymous) @ bridge.js:1
document.dispatchEvent @ bridge.js:1
(anonymous) @ VM103:1
WebFrame.(anonymous function) @ VM101 web-frame.js:56
electron.ipcRenderer.on @ VM83 web-frame-init.js:36
emit @ VM18 events.js:182
[WORKER] onerror (5) ["Cannot read property 'mountedHandles' of undefined", "", 0, 0, TypeError: Cannot read property 'mountedHandles' of undefined
at Object.didMount (http://127.0.0…]

**Comment by xiaofuzi** [comment]
支付宝小程序直接引用转换后 的组件库需要经过 alipay-compiler 命令编译
