### ISSUE TITLE
支付宝小程序引入之后 使用组件报错

### ISSUE THREAD

**Issue by KianReed** [ant-move/Vant-Aliapp#4]
TypeError: Cannot read property 'mountedHandles' of undefined
    at Object.didMount (http://127.0.0.1:59536/index.worker.js?t=1578388842597:9182:76)
    at http://127.0.0.1:59536/index.worker.js?t=1578388842597:7942:14
    at Array.forEach (<anonymous>)
    at Object.ctx.(anonymous function) (http://127.0.0.1:59536/index.worker.js?t=1578388842597:7941:23)
    at a (https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:19395)
    at te (https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:30473)
    at n.ready (https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:38174)
    at He.updateComponents (https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:51629)
    at https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:51758
    at He.batchedUpdates (https://gw.alipayobjects.com/os/xpaas-appx-17-0/6912afa1-1f49-4760-816e-f37b998501e7/af-appx.worker.ide.min.js:7:51863)

**Comment by KianReed** [comment]
已经解决
